# Thanks to Stefan Stranger
# https://stefanstranger.github.io/2018/12/30/UseAzurePipelinesToPublishPowerShellModule/

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: azure-template.yml # Template reference

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: azure-template.yml # Template reference

- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-template.yml # Template reference

- job: Publish
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - task: PowerShell@2
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    displayName: 'Run publish task'
    env:
      psgallery: $(NugetAPIKey)
    inputs:
      targetType: Inline
      script: ./build.ps1 -Publish
