jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

steps:
- powershell: ./build.ps1 -Bootstrap -Test
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testRunner: NUnit
    testResultsFiles: '**/TestResults.xml'
  condition: succeededOrFailed()
