steps:
- powershell: ./build.ps1 -Bootstrap -Test
  displayName: 'Run tests'
  pwsh: true

- task: PublishTestResults@2
  inputs:
    testRunner: NUnit
    testResultsFiles: '**/TestResults.xml'
  condition: succeededOrFailed()
