steps:
- task: PowerShell@2
  displayName: 'Run tests'
  inputs:
    script: ./build.ps1 -Bootstrap -Test
    pwsh: true

- task: PublishTestResults@2
  inputs:
    testRunner: NUnit
    testResultsFiles: '**/TestResults.xml'
  condition: succeededOrFailed()
